// Curated re-export of lucide-react — the approved icon set for Mosaic UI
// (simple line-icon style, no fills).
//
// Import icons from here rather than 'lucide-react' directly, so the set
// used across apps stays a deliberate, documented list instead of any of
// lucide's 1000+ icons being pulled in ad hoc.
//
// The set is curated by role rather than copied wholesale: most concepts map
// onto lucide icons in one consistent outline style, and concepts lucide has
// no equivalent for — education-domain modes, the product bot, font-size
// controls — live in customIcons.ts as real SVG artwork instead. Don't
// force-fit a lucide icon onto one of those concepts: add to this file when
// a component needs a lucide icon not yet listed, and add real artwork to
// customIcons.ts when it needs a custom one.

export {
  // Status / feedback
  Check,
  CheckCircle,
  CheckCircle2,
  CheckCheck,
  Circle,
  X,
  XCircle,
  AlertCircle,
  AlertTriangle,
  Info,
  HelpCircle,
  // Navigation / disclosure
  ChevronDown,
  ChevronUp,
  ChevronLeft,
  ChevronRight,
  ChevronDownCircle,
  ChevronUpCircle,
  ChevronLeftCircle,
  ChevronRightCircle,
  ChevronsDown,
  ChevronsUp,
  ChevronsLeft,
  ChevronsRight,
  ArrowLeft,
  ArrowRight,
  ArrowUp,
  ArrowDown,
  ArrowLeftCircle,
  ArrowRightCircle,
  ArrowUpCircle,
  ArrowDownCircle,
  ArrowLeftRight,
  ArrowUpDown,
  ExternalLink,
  Menu,
  Hamburger,
  PanelLeft,
  MoreVertical,
  MoreHorizontal,
  Expand,
  Fullscreen,
  Minimize2,
  CornerDownLeft,
  CornerDownRight,
  Locate,
  Move,
  // UI chrome for the design system's own tooling (the Icons foundation
  // page's list/grid view toggle).
  LayoutList,
  LayoutGrid,
  // Actions
  Plus,
  Minus,
  Trash2,
  Pencil,
  Search,
  Loader2,
  RefreshCw,
  RotateCcw,
  Download,
  Upload,
  Send,
  Mic,
  MicOff,
  Copy,
  Filter,
  FilterX,
  ListFilter,
  Link,
  Paperclip,
  // People / roles (cross-cohort — student, teacher, admin all use these)
  User,
  Users,
  UserPlus,
  LogOut,
  Crown,
  // Common entities / objects
  Calendar,
  Clock,
  Bell,
  Settings,
  Lock,
  Unlock,
  Mail,
  FileText,
  File,
  FileUp,
  FileBarChart,
  BookOpen,
  Bookmark,
  GraduationCap,
  Eye,
  EyeOff,
  Archive,
  Folders,
  FolderOpen,
  Camera,
  Flag,
  Flame,
  Gauge,
  Globe,
  Grid,
  Group,
  Heart,
  Hourglass,
  Lightbulb,
  Megaphone,
  MessageCircle,
  MessageSquareText,
  Phone,
  PhoneOff,
  Pin,
  PictureInPicture,
  ShoppingBag,
  Speaker,
  Square,
  Star,
  Target,
  ThumbsDown,
  ThumbsUp,
  Timer,
  Award,
  Coins,
  Rocket,
  AppWindow,
  List,
  // Media (AudioPlayer)
  Play,
  PlayCircle,
  Pause,
  Volume2,
  Video,
  VideoOff,
} from 'lucide-react';

/** Standard icon pixel sizes used across the component library. */
export const ICON_SIZE = {
  sm: 16,
  md: 20,
  lg: 24,
} as const;
